### PR TITLE
Fix excessive CPU usage by using SetCommTimeouts

### LINKED ISSUE #8: Set serial port timeout to avoid high CPU usage
@ngbrown has suggested me in #2 that we should call [SetCommTimeouts()](https://docs.microsoft.com/ja-jp/windows/win32/api/winbase/nf-winbase-setcommtimeouts) to avoid high CPU usage. I think we need to set `0` to  `ReadIntervalTimeout`, but I cannot evaluate it because I cannot reproduce the problem (high CPU usage) on my environment (Windows 10 + USB serial converter + Raspberry Pi 4 (Raspberry Pi OS AAArch64)). So I need the help.

### PR DESCRIPTION
**Pull request by ngbrown**
Closes #8 

As mentioned in https://github.com/YaSuenag/SimpleCom/issues/2#issuecomment-813677549, the high CPU was caused by an interaction with other programs that were resetting the COM port timeouts on exit. TeraTerm specifically was resetting the timeouts on close. When SimpleCom opened the serial port after TeraTerm had closed it, the reset the value to `MAXDWORD` ([see code](https://osdn.net/projects/ttssh2/scm/svn/blobs/head/trunk/teraterm/teraterm/commlib.c)) resulted constant CPU polling instead of waiting for the overlapped event.

The fix is to set the expected timeouts on COM port open.

This pull request also clears the `serialReadOverlapped` structure on creation, just to be tidy.

### CODE REVIEW

File: SimpleCom/SimpleCom.cpp [hunk 1]
```diff
@@ -177,7 +177,21 @@ int _tmain(int argc, LPCTSTR argv[])
 	SetCommMask(hSerial, EV_RXCHAR);
 	SetupComm(hSerial, 1, 1);
 
+	COMMTIMEOUTS comm_timeouts;
+	GetCommTimeouts(hSerial, &comm_timeouts);
+	comm_timeouts.ReadIntervalTimeout = 1;
```
Comment (YaSuenag) [inline SimpleCom/SimpleCom.cpp:182]: As I mentioned in https://github.com/YaSuenag/SimpleCom/issues/2#issuecomment-813768777 , why did you set `1` to `ReadIntervalTimeout`? I think it can be zero, and it is nature.

Comment (ngbrown) [reply SimpleCom/SimpleCom.cpp:182]: When other programs set `ReadIntervalTimeout=MAXDWORD`, on exit, and if the next user of the COM port doesn't set it to something else, then "the read operation is to return immediately with the bytes that have already been received, even if no bytes have been received".

"A value of zero indicates that interval time-outs are not used." I don't think this is what is wanted either. With a value of `1` the thread loop will timeout and have a chance to address other flags such as `terminated` at least every 1 ms. If anything, it probably could be increased to 100 ms or so, but at a 1 ms period, the CPU issue was resolved.

Comment (YaSuenag) [reply SimpleCom/SimpleCom.cpp:182]: I guess the behavior (the loop is not so busy even if `ReadIntervalTimeout` is set to 1ms) is due to `ReadTotalTimeoutConstant`. You mentioned `terminate` flag for example, but I don't think so because SimpleCom would issue `CancellIoEx()` for `hSerial` (handle for serial line) after terminating StdInRedirector.
In addition, I'm concern the loop would wakeup excessively with 1ms timeout.

Thus I think it is prefer to disable timeout. What do you think?

Comment (ngbrown) [reply SimpleCom/SimpleCom.cpp:182]: It's worth trying both 0 and 100 to see if there's any difference.

**Comment by YaSuenag** [comment]
I want to set `0` here if there are no big difference from 1 / 100.
However I've not yet reproduce the problem as I said before. Could you evaluate it?

**Comment by YaSuenag** [comment]
@ngbrown I pushed my suggestion https://github.com/YaSuenag/SimpleCom/commit/4112f7d8906649deeedfc59ef807e440a9807a30

* Set `0` to `ReadIntervalTimeout`, then it works fine with my Raspberry Pi 4 (USB OTG serial port)
* Remove zero-clear code for `serialReadOverlapped` because it has already been cleared in below: https://github.com/YaSuenag/SimpleCom/blob/5baaf61f880949ea2b9c4e64b462d82ef1eab6a9/SimpleCom/SimpleCom.cpp#L31

I want to know whether this change (branch which includes your change: https://github.com/YaSuenag/SimpleCom/tree/patch-3) resolves CPU usage problem. Could you evaluate it? If it is ok, I want to merge this. (your contribution will be recorded in commit log of course)

**Comment by YaSuenag** [comment]
If I hear no comments within a week, I will merge my branch.

**Comment by YaSuenag** [comment]
@ngbrown I merged your contribution with my commit. Thanks for your contribution!
